apiVersion: krateo.io/v1alpha1
kind: Patch
metadata:
  name: compositiondefinition-status-card-color
spec:
  from:
    objectReference:
      apiVersion: core.krateo.io/v1alpha1
      kind: CompositionDefinition
      name:  {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
    fieldPath: status
  to:
    objectReference:
      apiVersion: templates.krateo.io/v1alpha1
      kind: Widget
      name: template-{{ .Release.Name }}-card
      namespace: {{ .Release.Namespace }}
    fieldPath: spec.app.template.color
    transform: ${ .conditions[] | select(.type == "Ready") | if .status == "False" then "yellow" elif .status == "True" then "red" else "grey" end }